# Config format schema number
format_version: 4

###################
## Model options
model_params:
  model_architecture: "resnet50"

  history_num_frames: 0
  history_step_size: 1
  history_delta_time: 0.1

  future_num_frames: 12
  future_step_size: 1
  future_delta_time: 0.1

###################
## Input raster parameters
raster_params:
  # raster image size [pixels]
  raster_size:
    - 224
    - 224
  # raster's spatial resolution [meters per pixel]: the size in the real world one pixel corresponds to.
  pixel_size:
    - 0.5
    - 0.5
  # From 0 to 1 per axis, [0.5,0.5] would show the ego centered in the image.
  ego_center:
    - 0.25
    - 0.5
  map_type: "py_semantic"

  # the keys are relative to the dataset environment variable
  satellite_map_key: "aerial_map/aerial_map.png"
  semantic_map_key: "semantic_map/semantic_map.pb"
  dataset_meta_key: "meta.json"

  # e.g. 0.0 include every obstacle, 0.5 show those obstacles with >0.5 probability of being
  # one of the classes we care about (cars, bikes, peds, etc.), >=1.0 filter all other agents.
  filter_agents_threshold: 0.5

  # whether to completely disable traffic light faces in the semantic rasterizer
  disable_traffic_light_faces: False

  # when set to True performs a flip inside the rasteriser.
  # Set it to False for models trained before December.
  # In that case visualisation will be flipped (we've removed the flip there) but the model's input will be correct.
  origin_bottom: True

###################
## Data loader options
train_data_loader:
  key: "scenes/train.zarr"
  batch_size: 12
  shuffle: True
  num_workers: 16
  perturb_probability: 0.5

val_data_loader:
  key: "scenes/validate_0.zarr"
  batch_size: 12
  shuffle: False
  num_workers: 16

###################
## Train params
train_params:
  checkpoint_every_n_steps: 10000
  max_num_steps: 5
  eval_every_n_steps: 10000
