[tool.black]
line-length = 119
exclude = '/l5kit\/data\/proto\/*/'

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 119
skip='l5kit\/data\/proto'

[tool.pytest.ini_options]
xfail_strict=true