name: L5Kit-tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  CI-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - name: Set up Python ${{ matrix.python-version }} and Poetry
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
        python-version: ${{ matrix.python-version }}
    - uses: Gr1N/setup-poetry@v2
      with:
        poetry-version: 1.0.10
    - name: Install dependencies
      working-directory: l5kit
      run: |
        poetry install
    - name: Lint project
      working-directory: l5kit
      run: |
        ./run_tests.sh lint
    - name: Import sorting project
      working-directory: l5kit
      run: |
        ./run_tests.sh isort
    - name: Run tests
      working-directory: l5kit
      run: |
        ./run_tests.sh tests
    - name: Check types with mypy
      working-directory: l5kit
      run: |
        ./run_tests.sh types
